const fs = require("fs");
const { promisify } = require("util");

const writeFile = promisify(fs.writeFile);

const envData = `# Generated by setup.js
REACT_APP_GOOGLE_API_KEY=""
REACT_APP_API_URL=""
REACT_APP_CLIENT_ID=""
REACT_APP_CLIENT_SECRET=""
`;


const configFiles = [{
        filename: ".env",
        content: envData
    },
];

configFiles.forEach(file => {
    if (!fs.existsSync(file.filename)) {
        writeFile(file.filename, file.content, "utf8").catch(err => {
            console.log(err);
        });
    }
});